version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the Spring Boot application"
      - ./mvnw package
artifacts:
  files: target/*.jar
