#version: 0.2
#
#phases:
#  install:
#    runtime-versions:
#      java: corretto11
#    commands:
#      - echo "Installing dependencies"
#  build:
#    commands:
#      - echo "Building the Spring Boot application"
#      - ./mvnw package
#artifacts:
#  files: target/*.jar


version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      # Set the AWS region
      - export AWS_DEFAULT_REGION=your-region

  build:
    commands:
      # Build the Spring Boot application using Maven
      - mvn clean install

artifacts:
  files: target/customer-service-0.0.1-SNAPSHOT.jar
  discard-paths: yes

cache:
  paths:
    - ~/.m2/repository
